import { ArrowRight, Brain, HeartHandshake, MapPin, Phone, School, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
import { areas, blogs, services, site } from '@/data/content';

function Header(){return <header className="nav"><div className="container navin"><a className="brand" href="/">Altın Lale<span>Sincan / Ankara</span></a><nav className="links"><a href="#hizmetler">Programlar</a><a href="#surec">Süreç</a><a href="#bolgeler">Bölgeler</a><a href="#blog">Rehber</a><a className="btn" href={site.phoneHref}>Hemen Ara</a></nav></div></header>}
function Footer(){return <footer className="footer"><div className="container footgrid"><div><h2>{site.name}</h2><p>Çocuğun gelişim ihtiyaçlarına göre planlanan özel eğitim ve rehabilitasyon desteği.</p></div><div><b>İletişim</b><p>{site.phone}</p><p>{site.address}</p></div><div><b>Hızlı Bağlantı</b><p><a href={site.maps}>Yol Tarifi</a></p><p><a href={site.whatsapp}>WhatsApp</a></p></div></div></footer>}
export default function Home(){return <><Header/><main><section className="hero"><div className="container heroGrid"><div><span className="eyebrow">Sincan Özel Eğitim ve Rehabilitasyon Merkezi</span><h1 className="h1">Her çocuğun potansiyeline ulaşmasına destek oluyoruz.</h1><p className="lead">Altın Lale Özel Eğitim ve Rehabilitasyon Merkezi; Sincan ve Ankara çevresinde bireysel eğitim, grup eğitimi, otizm, dil-konuşma ve öğrenme güçlüğü alanlarında aileyle birlikte ilerleyen güvenli bir destek süreci sunar.</p><div className="actions"><a className="btn" href={site.phoneHref}><Phone size={18}/> Hemen Ara</a><a className="btn alt" href={site.maps}><MapPin size={18}/> Yol Tarifi Al</a></div><div className="stats"><div className="stat"><b>01</b>Çocuğa özel planlama</div><div className="stat"><b>02</b>Aileyle düzenli takip</div><div className="stat"><b>03</b>Sıcak ve güvenli ortam</div></div></div><div className="visual"><div className="floating"><Sparkles color="#d8b35a"/><h3>Premium, sakin ve güven veren eğitim atmosferi</h3><p>İlk görüşmeden gelişim takibine kadar aileyi bilgilendiren, çocuğun ihtiyacına göre ilerleyen yapı.</p></div></div></div></section>
<section id="hizmetler" className="section"><div className="container"><h2 className="title">Eğitim Programlarımız</h2><p className="subtitle">Her çocuğun ihtiyacı farklıdır. Bu yüzden eğitim sürecini tek tip değil; gözlem, değerlendirme, aile beklentisi ve gelişim hedeflerine göre planlıyoruz.</p><div className="cards">{services.map(([slug,title,desc],i)=><a className="card" key={slug} href={`/hizmetler/${slug}`}><div className="icon">{i%3===0?<Brain/>:i%3===1?<UsersRound/>:<HeartHandshake/>}</div><h3>{title}</h3><p>{desc}</p><b>Detaylı İncele <ArrowRight size={15}/></b></a>)}</div></div></section>
<section id="surec" className="section"><div className="container dark"><h2 className="title">Aileye güven veren şeffaf süreç</h2><p className="subtitle" style={{color:'#d9e5e1'}}>Altın Lale’de amaç yalnızca eğitim vermek değil; aileyi sürece dahil ederek çocuğun gelişimini sürdürülebilir şekilde desteklemektir.</p><div className="process"><div className="step"><b>1</b><h3>İlk Görüşme</h3><p>Çocuğun ihtiyaçları ve aile beklentileri dinlenir.</p></div><div className="step"><b>2</b><h3>Değerlendirme</h3><p>Gelişim alanları ve desteklenmesi gereken beceriler belirlenir.</p></div><div className="step"><b>3</b><h3>Planlama</h3><p>Bireysel hedefler ve eğitim akışı oluşturulur.</p></div><div className="step"><b>4</b><h3>Takip</h3><p>Gelişim süreci aileyle düzenli paylaşılır.</p></div></div></div></section>
<section id="bolgeler" className="section"><div className="container"><h2 className="title">Sincan ve çevresine yakın konum</h2><p className="subtitle">Mareşal Çakmak, Ankara Caddesi üzerindeki merkezi konumumuzla Sincan, Eryaman, Etimesgut, Yenikent ve çevre bölgelerden kolay ulaşım sağlar.</p><div className="areaGrid">{areas.map(a=><a className="pill" href={`/bolgeler/${a.toLowerCase().replaceAll('ı','i').replaceAll('ö','o').replaceAll('ü','u').replaceAll('ş','s').replaceAll('ç','c').replaceAll('ğ','g')}-ozel-egitim-merkezi`} key={a}>{a} Özel Eğitim</a>)}</div></div></section>
<section id="blog" className="section"><div className="container"><h2 className="title">Aileler için özel eğitim rehberi</h2><div className="blog">{blogs.map((b,i)=><a key={b} href={`/blog/${i+1}`}>{b}</a>)}</div></div></section>
<section className="section"><div className="container cta"><div><h2 className="title">Çocuğunuz için ilk adımı birlikte planlayalım.</h2><p className="subtitle">Bilgi almak, görüşme oluşturmak veya yol tarifi almak için hemen iletişime geçebilirsiniz.</p></div><div className="actions"><a className="btn" href={site.phoneHref}>Hemen Ara</a><a className="btn alt" href={site.whatsapp}>WhatsApp</a></div></div></section></main><Footer/><div className="mobilebar"><a href={site.phoneHref}>Ara</a><a href={site.whatsapp}>WhatsApp</a><a href={site.maps}>Yol Tarifi</a></div></>}
